#!/bin/bash

# File locations
extensionName="Gnoti@AntonVA.dev"
extensionUserPath=$HOME"/.local/share/gnome-shell/extensions/"

extensionPath=${extensionUserPath}${extensionName}

# Abort if error
set -e

function message() {
    # $1 = type , $2 = message
    # Message types
    # info
    # warning
    # error
    if [[ -z "${1}" ]] || [[ -z "${2}" ]]; then
      return
    fi

    local RED="\e[31m"
    local GREEN="\e[32m"
    local YELLOW="\e[33m"
    local RESET="\e[0m"
    local MESSAGE_TYPE=""
    local MESSAGE=""
    MESSAGE_TYPE="${1}"
    MESSAGE="${2}"

    case ${MESSAGE_TYPE} in
      info) echo -e "  [${GREEN}+${RESET}] INFO: ${MESSAGE}";;
      warn) echo -e "  [${YELLOW}*${RESET}] WARNING: ${MESSAGE}";;
      error) echo -e "  [${RED}!${RESET}] ERROR: ${MESSAGE}";;
      *) echo -e "  [?] UNKNOWN: ${MESSAGE}";;
    esac
}
case $1 in
    "--help"| "--h")
        message info 'Usage:'
        echo '      ./setup [FLAG] [POSITION]'
        echo '      Flags:'
        echo '          --install    (or --i)               Installs the extension with the chosen position.'
        echo '          --uninstall  (or --u)               Remove Gnoti.'
        echo '          --test       (or --t)               Test the extension'
        echo '      Positions:'
        echo '          topright'
        echo '          topleft'
        echo '          topcenter'
        exit 1
        ;;

    "--install"| "--i")
        case "$2" in
            topright) position="Main.messageTray._bannerBin.x = Right.topright(); // Top right";;
            topleft) position="Main.messageTray._bannerBin.x = Left.topleft(); // Top left";;
            topcenter) position="// Top center";;
            *) message error "Unknown position: $2" && exit 1;;
        esac
        shift;shift;

        mkdir -p ${extensionPath}
        cp -r ./src/* ${extensionPath}/
        touch ${extensionPath}/config.json
        sed "30 i ${position}" ./src/extension.js &> ${extensionPath}/extension.js
        message info "Files copied to ${extensionPath}"

        if [[ "${XDG_SESSION_TYPE}" == "x11" ]]; then
            message info "Restarting Gnome Shell"
            busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")' &> /dev/null
            message info "Gnoti has been succesfully installed!"
            exit 1
        else
            message info "Gnoti has been succesfully installed!"
            message warn "Please log out and then log back in for the changes to take effect."
            exit 1
        fi
        ;;
    
    "--uninstall"| "--u")
        rm -rf ${extensionPath}
        message info "Removed files from this location${extensionPath}"

        if [[ "${XDG_SESSION_TYPE}" == "x11" ]]; then
            message info "Restarting Gnome Shell"
            busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")' &> /dev/null
            message info "Gnoti has been succesfully removed!"
            exit 1
        else
            message info "Gnoti has been succesfully Removed!"
            message warn "Please log out and then log back in for the changes to take effect."
            exit 1
        fi
        ;;

    "--test"| "--t")
        notify-send "Notification" "This is my new position!!!"
        exit 1
    ;;

    *)
        message error "Unknown option: $*"
        exit 22
        ;;
esac
